spring:
  flyway:
    schemas: checkin
    create-schemas: true
    url: jdbc:mariadb://localhost:3322/
    user: root
    password: iamgroot
  datasource:
    url: jdbc:mariadb://localhost:3322/checkin
    username: root
    password: iamgroot
    driver-class-name: org.mariadb.jdbc.Driver
